<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net48</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<AssemblyName>BoxMetPlugin</AssemblyName>
		<RootNamespace>BoxMetPlugin</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="AcCoreMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2022\AcCoreMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AcDbMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2022\AcDbMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="AcMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2022\AcMgd.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>